server:
  port: 80


likes:
  - music
  - game


likes2: [music, game]

user:
  name: zhangsan
  age: 18

user1:
  name: zhangsan
  age: 18

users:
  - name: zhangsan
    age: 18
  - name: lisi
    age: 18


users2:
  -
    name: zhangsan
    age: 18
  -
    name: lisi
    age: 18

users3: [{name:zhangsan, age:18}, {name:lisi, age:18}]

country: 中国


baseDir: c:\windows


tempDir: c:\windows\temp
#使用属性名方式引用数据
tempDir1: ${baseDir}\temp

#创建类封装数据
# 使用spring帮我们去加载数据到对象，一定要告诉spring加载这组信息1
# 使用时候从spring中之间获取信息使用


datasource:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost/springboot
  username: root
  password: a520520a