server:
  port: 80

# 配置数据库信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/test
    username: root
    password: a520520a












datasource:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost/test
  username: root
  password: a520520a
  likes:
    - music
    - game


likes: [music, game]

user:
  name: zhangsan
  age: 18

user1:
  name: zhangsan
  age: 18

users:
  - name: zhangsan
    age: 18
  - name: lisi
    age: 18


users2:
  -
    name: zhangsan
    age: 18
  -
    name: lisi
    age: 18

users3: [{name:zhangsan, age:18}, {name:lisi, age:18}]

country: 中国


baseDir: c:\windows


tempDir: c:\windows\temp
#使用属性名方式引用数据
tempDir1: ${baseDir}\temp

#创建类封装数据
# 使用spring帮我们去加载数据到对象，一定要告诉spring加载这组信息1
# 使用时候从spring中之间获取信息使用
